// <auto-generated />
using ElectronicGadgets.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicGadgets.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241103075017_AddCategoryToDbAndSeedTable")]
    partial class AddCategoryToDbAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicGadgets.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mobile phones with advanced features",
                            DisplayOrder = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Portable personal computers",
                            DisplayOrder = 2,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compact touchscreen devices",
                            DisplayOrder = 3,
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Wearable devices with smart features",
                            DisplayOrder = 4,
                            Name = "Smartwatches"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Electronic devices for viewing multimedia content",
                            DisplayOrder = 5,
                            Name = "Televisions"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Devices used to capture photographs or videos",
                            DisplayOrder = 6,
                            Name = "Cameras"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Personal audio listening devices",
                            DisplayOrder = 7,
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Devices that amplify sound",
                            DisplayOrder = 8,
                            Name = "Speakers"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Devices used to play video games",
                            DisplayOrder = 9,
                            Name = "Gaming Consoles"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Electronic devices for visual display",
                            DisplayOrder = 10,
                            Name = "Monitors"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
